CREATE TABLE "Pricing_Info" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"PRODUCT_ID"	INTEGER,
	"ZIPCODE"	TEXT,
	"UNIT"	TEXT,
	"STORE_ID"	INTEGER,
	"PRICE"	REAL,
	"CREATED_DATE"	TEXT,
	"ITEM_NAME"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("PRODUCT_ID") REFERENCES "Products"("PRODUCT_ID"),
	FOREIGN KEY("STORE_ID") REFERENCES "Stores"("STORE_ID"),
	FOREIGN KEY("ZIPCODE") REFERENCES "US_Zip_Codes"("ZIPCODE")
);