CREATE TABLE "Pricing_Info" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"PRODUCT_ID"	INTEGER,
	"ZIPCODE"	TEXT,
	"UNIT"	TEXT,
	"STORE_ID"	INTEGER,
	"PRICE"	REAL,
	"CREATED_DATE"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);