CREATE TABLE "User_Alerts" (
	"ALERT_ID" INTEGER PRIMARY KEY AUTOINCREMENT,
	"USER_NAME" TEXT NOT NULL,
	"CATEGORY" TEXT NOT NULL,
	"STORE_ID" INTEGER,
	"THRESHOLD_PRICE" REAL NOT NULL,
	"ZIPCODE" TEXT NOT NULL,
	"CREATED_DATE" TEXT DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" TEXT,
	"MODIFIED_DATE" TEXT,
	"MODIFIED_BY" TEXT,
	FOREIGN KEY("ZIPCODE") REFERENCES "US_Zip_Codes"("ZIPCODE"),
	FOREIGN KEY("STORE_ID") REFERENCES "Stores"("STORE_ID")
);
